Fix a lot of errors
Handle NPE in TelephonyManager

ITelphony service instance could be null at boot up
when device activation is taking place.

An additional NPE is handled here compared to this commit's original
form (If72622a2d22a20b1ce909134ce4c6446b132dffe):
  NPE exception handling in getDataEnabled has been backported from:
  GpsLocationProvider: Read data enabled status from TelephonyManager.
  I0333050d2a5b8d484466e1b1914dcfb9965398c9

  This addresses BUGDUMP-1125891

Change-Id: I89468a2b1cf680acb1edfa27ad1ffbfb145caede

Prevent IndexOutOfBoundsException

Change-Id: Ie48435bf41c6c9738a4f87045d018c03fc612c35

Fix to avoid UI freeze issue

Due to some race condition in WindowManagerService, Screenshot
layer remains as topmost and buffers are not flipped hence
no updates seen on the screen. So, trying to destroy persistent
layer explicitly if freeze timeout expires 6sec.

Change-Id: Ibe295550a7431a4f633a57e7dfab0cbda102ab87

Fix NPE in TextUtils

return false if String is null or empty. Fix NPE too.

see https://code.google.com/p/android/issues/detail?id=24965

Change-Id: I7ce8a98f1e0753e905410ec469cd76a8b542d484

Handle IllegalStateException from Surface.lockCanvas

Symptom: SystemServer crash because of this exception on startingWindow
Root Cause: IllegalStateException from Surface.lockCanvas
Solution: handle IllegalStateException from Surface.lockCanvas

Change-Id: Ifb1b3b72877dfd9994ebf17dcef4778f88821301

Fix ListView is not scrolled properly with arrows

According to ListView's layoutChildren logic, it detaches all children
and rebuilds its children based on visible area which might omit
invisible elements in the adapter.

In this case, arrowScroll methods only tries to find next scroll
candidates from its children so user is unable to scroll more with
D-pad.

This fixes the issue by look forward next child among the adapter as
well as children.

Bug: 7346868

Change-Id: I01ab19ad899b5bcb5ab420ddf08c9ffd136933d1

Handle NPE due to threading race

Change-Id: I6eab5bc3d687edfa6f0839e439b3314bed4fdcea

Fix NPE in updateEmptyShadeView() upon screen rotation

FATAL EXCEPTION: main
Process: com.android.systemui, PID: 19252

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.systemui.statusbar.EmptyShadeView.willBeGone()' on a null object reference
  at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateEmptyShadeView(NotificationStackScrollLayout.java:2291)
  at com.android.systemui.statusbar.phone.NotificationPanelView.updateEmptyShadeView(NotificationPanelView.java:2058)
  at com.android.systemui.statusbar.phone.NotificationPanelView.updateQsState(NotificationPanelView.java:1181)
  at com.android.systemui.statusbar.phone.NotificationPanelView.setQsScrimEnabled(NotificationPanelView.java:2065)
  at com.android.systemui.statusbar.phone.PhoneStatusBar$11.onVerticalChanged(PhoneStatusBar.java:1079)

Change-Id: I010b1a23301385f7a2e9e4863d9e2d1ebcde1825

Deadlock in PackageInstallerSession

On rare ocasions deadlock occur between
AcitityManagerService.getServices(), PackageManagerService.dump()
and PackageInstallerSession.dispatchSessionFinished()

Application calling getRunningServices():
This thread will first take ActivityManagerService.this lock, then
when checking UID permissions with package manager it wants
the mPackages lock

PackageInstaller thread:
mHandlerCallback takes mLock and executes dispatchSessionFinished()
which later will wait for ActivityManagerService.this lock to be
relesed in PendintIntentRecord.sendInner(). (this lock is now held by
call to getServices()).

PackageManagerService thread:
This thread is performing a dump, that could be requested by an
application or by system. To perform dump it takes mPackages lock
then later to dump PackageInstallSesssion it needs to hold mLock
already held by PackageInstaller thread.

The simplest solution to this deadlock is to modify the callback
code in PackageInstallerSession. The call dispatchSessionFinished()
should never be called while holding PackageInstallerSession.mLock,
so moving this call outside the lock will resolve this problem.

Change-Id: I545ccedf89ca90077122ac77d22d7aaed0f7f1fb

Handle IllegalArgumentException

In some cases startInputInnerLocked() throws
IllegalArgumentException which needs to be handle

Change-Id: I315cb46b1d16c2862989cb9c0c10ed6613884522

Fix the NullPointerException

Checking Account object for NULL before accessing it.

Change-Id: Iae3e331edfda238ecb0c6d5d32b15329b1dfee0b

Handle ActivityNotFoundException for contacts activity

Whenever contacts application is disabled or removed,
starting contacts activity in monkey test results in
ActivityNotFoundException. Catch such situation.

Change-Id: Ib6e50ca3418d1155305df66915a6c11a93bfe28d

Define priority for callerinfo selection

If a phone number has multiple contacts, then select a contact which contains user defined photo.

Change-Id: I0c86447e3d6f3dbf98c0bf87efe50bdd1c38faa4

Fix inconsistant display number format issue in Messaging application

The issue can be reproduced as follows
1. Create  a new sms.
2. Input a recipient
3. Edit message.
4. Add a recipient
5. Try to edit the message
After step 5, the numbers are not formatted in the same way

The issue is that PhoneNumberFormattingTextWatcher only process the
first phone number.  This patch use ", " and "; " as separator to
split the phone numbers and then format all of phone numbers one by
one.

Change-Id: I32d59259a0cf157551e7e4b84ae6e25e68a57443

Sometimes property service is slow to respond

Upon boot-up, telephony service will update the system property for
timezone and send out broadcast.The property service won’t handle
the update immediately if the init process was doing something
time-consuming. Meanwhile StatusBar(one broadcast register) may get
the outdated value by reading from system property, because the
update is not handled yet. Then wrong time will be displayed on
status bar

Change-Id: Ic29b7940b58e01651da4e0bafa7a88b902164bd0

Remove freezing window to fix UI freezing issue

In some corner case, some window is at exiting state, but can't be
removed. because the binder transact failed, and the state of window can't change
so that will still resizing window,This will result the windownmanger fall into freezing state

The fix will stop resizing this window when encounter this case

Change-Id: I3e41aacadcaaea197dd74d8b93a7ed73ee441ff1

Fix memory leak in MediaScannerConnection

This patch adds releasing of MediaScannerConnection in ClientProxy
after disconnecting and releasing of ClientProxy and
IMediaScannerService in disconnection sequence in
MediaScannerConnection.

Bug: 30150344

Change-Id: I1e162e4c9a0b7a741ace20480bcf06f3151a93bf

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>